name: CI Semantic Releaser

on:
  workflow_dispatch:
  push:
    branches: [ v1.16.x ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          extra_plugins: "semantic-release @semantic-release/exec conventional-changelog-conventionalcommits"
          branches: "v1.16.x"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Grant execute permission for gradlew
        if: steps.semantic.outputs.new_release_published == 'true'
        run: chmod +x gradlew

      - name: Setup forge mdk
        if: steps.semantic.outputs.new_release_published == 'true'
        run: ./gradlew init

      - name: Build with Gradle
        if: steps.semantic.outputs.new_release_published == 'true'
        run: ./gradlew build

      - name: Upload Release Asset
        if: steps.semantic.outputs.new_release_published == 'true'
        id: upload-release-asset
        uses: svenstaro/upload-release-action@v2
        with:
          body: "Version ${{steps.semantic.outputs.new_release_version}}"
          repo_name: DragonSurvivalTeam/DragonSurvivalReleases
          repo_token: ${{ secrets.RELEASE_KEY }}
          file: build/libs/*.jar
          tag: ${{ steps.semantic.outputs.new_release_version }}
          file_glob: true